---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: default             #需要访问多个命名空间且各自命名空间内权限不同时,命名空间不需要修改,便于其它命名空间复用。

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-full-access
  namespace: default             #需要访问多个命名空间且各自命名空间内权限不同时,修改Role命令空间。
rules:
- apiGroups:
  - ""
  - apps
  - autoscaling
  - batch
  - extensions
  - policy
  - rbac.authorization.k8s.io
  resources:
  - componentstatuses
  - configmaps
  - daemonsets
  - deployments
  - events
  - endpoints
  - horizontalpodautoscalers
  - ingress
  - jobs
  - limitranges
  - namespaces
  - nodes
  - pods
  - pods/log
  - pods/exec
  - pods/status
  - pods/portforward
  - persistentvolumes
  - persistentvolumeclaims
  - resourcequotas
  - replicasets
  - replicationcontrollers
  - statefulsets
  - serviceaccounts
  - services
  resourceNames:
  - canal-server-0
  - canal-server
  - emqx
  - emqx-0
  - emqx-1
  - emqx-2
  - mysql
  - mysql-0
  - traffic-manager
  verbs: ["*"]
- apiGroups: [ "" ]             #创建规则,允许list,因为resourceNames单资源控制字段不允许list, create。
  resources:
  - pods
  - services
  verbs:
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-view
  namespace: default             #需要访问多个命名空间且各自命名空间内权限不同时,修改RoleBinding命令空间。
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: default             #需要访问多个命名空间且各自命名空间内权限不同时,引用主体SA命名空间不变,因为使用同一个账号。
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-user-full-access