version: "3.8"

services:
  ros2:
    image: osrf/ros:humble-desktop-full
    container_name: ros2_container
    tty: true
    stdin_open: true
    devices:
     - /dev/dri:/dev/dri
    restart: always
    environment:
      - DISPLAY=${DISPLAY}
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - ROS_DOMAIN_ID=0
      - HOME=${HOME_DIR}
      - XDG_RUNTIME_DIR=/tmp/runtime-parallels
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    user: "${USER_ID}:${GROUP_ID}" #adapt as needed!
    volumes:
      # Why is the directory automatically created as root:root by Docker?
      # When the container starts, the `user: 1000:1000` setting hasn’t taken effect yet,
      # so Docker uses the default user (usually root) to create the directory first.
      # If the mount path doesn't exist on the host, Docker will create it using the default user!
      # share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers:/etc/sudoers:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - ${HOME_DIR}:${HOME_DIR}:rw #Share your home directory with write permissions. Make sure the mount path exactly matches the path on the host machine, otherwise you may encounter permission issues preventing log files from being written.
    working_dir: ${HOME_DIR}
    # command: /bin/bash -c "source /opt/ros/humble/setup.bash && bash"
    network_mode: host
    command:
      - /bin/bash
      - -c
      - |
        echo "source /home/parallels/ros_env2.sh"|| true && \
        exec rviz2

