# ca-example-com.certificate.cert-manager.yaml
# 参考：https://cert-manager.io/docs/usage/certificate/
# api参考：https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1alpha3.Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: znkjfw-com-tls
  # 指定证书生成到哪个工作空间，不指定的话，默认istio去这个命名空间拿证书会拿不到。
  namespace: istio-system
spec:
  #生成后证书的配置文件名称
  secretName: znkjfw-com-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - ZN Inc.
  dnsNames:
  - znkjfw.com
  - "*.znkjfw.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
